apiVersion: v1
kind: Service
metadata:
  name: myapp-envoy
  labels:
    app: myapp-envoy
spec:
  type: LoadBalancer
  ports:
#@ for i in range(0,100):
#@ port = 10000+i
  - protocol: TCP
    port: #@ port
    name: #@ "tcp" + str(port)
#@ end
  selector:
    app: myapp-envoy