apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  serviceName: "echo"
  replicas: 200
  selector:
    matchLabels:
      app: echo
  template:
    metadata:
      labels:
        app: echo
    spec:
      containers:
      - name: echo
        image: hashicorp/http-echo 
        env:
        - name: PODNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['statefulset.kubernetes.io/pod-name']
        args: 
          - "-listen=:5678"
          - "-text=$(PODNAME)"
        ports:
        - containerPort: 5678
          name: http
      nodeSelector:
        kubernetes.io/os: linux
